### ISSUE TITLE
Trait are open bound - Ent match Instrument

### ISSUE THREAD

**Issue by antilogos** [ddddirk/lotrdb#10]
When «searching by cards traits» and selecting «Ent», showing attachment, return Sylver Harp and Ent Draught.

**Comment by ddddirk** [comment]
This turns out to be harder to fix than I had hoped. Using regular expressions instead of strings doesn't seem to be an option. And checking for the correct case makes card name and card text case-sensitive as well, which is a bigger issue.

For now, it seems this is not a big issue, and I will put it on hold until I or someone else has a better idea of how to handle this.

**Comment by rmunn** [comment]
One way to fix this might be to, in the card trait search ONLY, change the user's input before searching:

1. Take user input, strip all leading and trailing whitespace.
2. Convert to lowercase.
3. Convert first character to uppercase.
4. Do a case-sensitive search for the trait.

That way, "Ent" can't match "Instrument".

**Comment by ddddirk** [comment]
Doing a case-sensitive search for trait only (not for name & text) was not an option with the current setup and requires a custom angular filter.

For now, I have implemented a quick workaround that involves "Ent" actually searching for " Ent" and adding a space in front of the traits list of every card. If this pops up again in the future, I'll re-evaluate.
